# Generated by Django 4.0.3 on 2022-04-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=15)),
                ('topic', models.CharField(max_length=30)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
