# Generated by Django 4.0.3 on 2022-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accountno',
            field=models.CharField(default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='post',
            name='amount_paid',
            field=models.CharField(default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(default='---', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='---', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.CharField(default='---', max_length=20),
        ),
    ]
